
Use_GPU: true
GPU_ID: 0

Camera_ID: 0

caffevis_caffe_root: "../../Program_files/caffe/"

# Paths to the yaml setting file of the models
# example:
# model_A : /path/to/the/setting/file/of/model_A
Model_config_path:
  Simpsons: "./model_simpsons_settings.yaml"
